//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessingSystem.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataProcessingSystemEntities : DbContext
    {
        public DataProcessingSystemEntities()
            : base("name=DataProcessingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
        public virtual DbSet<tblBarangay> tblBarangays { get; set; }
        public virtual DbSet<tblConductor> tblConductors { get; set; }
        public virtual DbSet<tblDrinkingWater> tblDrinkingWaters { get; set; }
        public virtual DbSet<tblFamilyPlanningMethod> tblFamilyPlanningMethods { get; set; }
        public virtual DbSet<tblHouse> tblHouses { get; set; }
        public virtual DbSet<tblIndividual> tblIndividuals { get; set; }
        public virtual DbSet<tblLog> tblLogs { get; set; }
        public virtual DbSet<tblOccupation> tblOccupations { get; set; }
        public virtual DbSet<tblPurok> tblPuroks { get; set; }
        public virtual DbSet<tblReason> tblReasons { get; set; }
        public virtual DbSet<tblRespondent> tblRespondents { get; set; }
        public virtual DbSet<tblSurvey> tblSurveys { get; set; }
        public virtual DbSet<tblToiletFacility> tblToiletFacilities { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblWasteDisposal> tblWasteDisposals { get; set; }
        public virtual DbSet<tblWaterSource> tblWaterSources { get; set; }
    }
}
