//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessingSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHouse()
        {
            this.tblIndividuals = new HashSet<tblIndividual>();
            this.tblSurveys = new HashSet<tblSurvey>();
        }
    
        public int ID { get; set; }
        public int houseNumber { get; set; }
        public string houseAddress { get; set; }
        public int purokID { get; set; }
        public int dwID { get; set; }
        public int wID { get; set; }
        public int wdID { get; set; }
        public int tfID { get; set; }
    
        public virtual tblDrinkingWater tblDrinkingWater { get; set; }
        public virtual tblPurok tblPurok { get; set; }
        public virtual tblToiletFacility tblToiletFacility { get; set; }
        public virtual tblWasteDisposal tblWasteDisposal { get; set; }
        public virtual tblWaterSource tblWaterSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIndividual> tblIndividuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSurvey> tblSurveys { get; set; }
    }
}
