//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessingSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSurvey
    {
        public int ID { get; set; }
        public int conductorID { get; set; }
        public int respondentID { get; set; }
        public int houseID { get; set; }
        public int endUserID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tblConductor tblConductor { get; set; }
        public virtual tblHouse tblHouse { get; set; }
        public virtual tblRespondent tblRespondent { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
